# Default configuration for all jobs
default:
  interruptible: true

# Define stages for pipeline
stages:
  - build
  - test
  - package
  - deploy

# Variables available to all jobs
variables:
  BUILD_TYPE: Release
  DOCKER_REGISTRY: $CI_REGISTRY
  DOCKER_TAG: $CI_COMMIT_SHA

# Cache configuration for faster builds
cache: &global_cache
  paths:
    - build/
    - .ccache/
    - .venv/
  policy: pull-push

# Job templates
.base_job:
  image: $CI_REGISTRY_IMAGE/base:latest
  cache:
    <<: *global_cache

.build_template:
  extends: .base_job
  stage: build
  artifacts:
    paths:
      - build/
      - dist/
    expire_in: 1 week

.test_template:
  extends: .base_job
  stage: test
  coverage: '/TOTAL.+ ([0-9]{1,3}%)/'
  artifacts:
    reports:
      coverage_report:
        coverage_format: cobertura
        path: coverage.xml
      junit: test-results.xml

.package_template:
  extends: .base_job
  stage: package
  artifacts:
    paths:
      - dist/
    expire_in: 1 month

.deploy_template:
  extends: .base_job
  stage: deploy
  rules:
    - if: $CI_COMMIT_TAG
      when: on_success
    - when: manual
  environment:
    name: production
